#!/usr/bin/env python3
# Copyright 2021-present StarRocks, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
from pathlib import Path
import sys


def write_array(out, data: bytes) -> None:
    out.write("static const unsigned char kEmbeddedDistributionData[] = {\n")
    for i, byte in enumerate(data):
        if i % 12 == 0:
            out.write("  ")
        out.write("0x{:02x}".format(byte))
        if i + 1 != len(data):
            out.write(",")
        if i % 12 == 11 or i + 1 == len(data):
            out.write("\n")
        else:
            out.write(" ")
    out.write("};\n\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate embedded SSB distribution C++ sources."
    )
    parser.add_argument("--input", required=True, help="Path to dists.dss")
    parser.add_argument("--output", required=True, help="Path to output .cc file")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    try:
        data = input_path.read_bytes()
    except OSError as exc:
        print("Failed to read {}: {}".format(input_path, exc), file=sys.stderr)
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by scripts/ssb/generate_embedded_distribution.py\n")
        out.write("#include \"distribution/embedded_distribution.h\"\n\n")
        out.write("namespace benchgen::ssb::internal {\n")
        write_array(out, data)
        out.write("const unsigned char* EmbeddedDistributionData() {\n")
        out.write("  return kEmbeddedDistributionData;\n")
        out.write("}\n\n")
        out.write("std::size_t EmbeddedDistributionSize() {\n")
        out.write("  return sizeof(kEmbeddedDistributionData);\n")
        out.write("}\n")
        out.write("}  // namespace benchgen::ssb::internal\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
