#!/usr/bin/env python3
# Copyright 2021-present StarRocks, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import sys


def sanitize_symbol(name):
    return "".join(c if c.isalnum() else "_" for c in name)


def write_array(out, symbol, data):
    out.write("const unsigned char {}[] = {{\n".format(symbol))
    for i, byte in enumerate(data):
        if i % 12 == 0:
            out.write("  ")
        out.write("0x{:02x}".format(byte))
        if i + 1 != len(data):
            out.write(",")
        if i % 12 == 11 or i + 1 == len(data):
            out.write("\n")
        else:
            out.write(" ")
    out.write("};\n\n")


def main():
    parser = argparse.ArgumentParser(
        description="Generate embedded distribution C++ sources."
    )
    parser.add_argument(
        "--distribution-dir",
        default="generated",
        help="Directory containing distribution files (default: generated)",
    )
    parser.add_argument(
        "--output",
        default="generated/tpcds_embedded_dist.cc",
        help="Output C++ source file (default: generated/tpcds_embedded_dist.cc)",
    )
    parser.add_argument(
        "--files",
        default="tpcds.idx",
        help="Comma-separated list of distribution files to embed (default: tpcds.idx)",
    )
    args = parser.parse_args()

    files = [name.strip() for name in args.files.split(",") if name.strip()]
    if not files:
        print("No files specified", file=sys.stderr)
        return 1

    entries = []
    for name in files:
        path = os.path.join(args.distribution_dir, name)
        try:
            with open(path, "rb") as handle:
                data = handle.read()
        except OSError as exc:
            print("Failed to read {}: {}".format(path, exc), file=sys.stderr)
            return 1
        entries.append((name, data))

    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(args.output, "w", newline="\n") as out:
        out.write("// Generated by scripts/generate_embedded_distribution.py\n")
        out.write("#include \"distribution/embedded_distribution_data.h\"\n\n")
        out.write("namespace benchgen::tpcds::internal {\n\n")
        symbols = []
        for name, data in entries:
            symbol = "kEmbedded_{}".format(sanitize_symbol(name))
            symbols.append((name, symbol))
            write_array(out, symbol, data)
        out.write("const EmbeddedDistributionFile kEmbeddedDistributionFiles[] = {\n")
        for name, symbol in symbols:
            out.write("  {\"%s\", %s, sizeof(%s)},\n" % (name, symbol, symbol))
        out.write("};\n\n")
        out.write("const size_t kEmbeddedDistributionFileCount =\n")
        out.write("    sizeof(kEmbeddedDistributionFiles) / sizeof(kEmbeddedDistributionFiles[0]);\n")
        out.write("\n}  // namespace benchgen::tpcds::internal\n")

    print("Wrote {}".format(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
